### ISSUE TITLE
Demos/examples not working

### ISSUE THREAD

**Issue by pavelloz** [BlinkID/blinkid-imagecapture-in-browser#19]
Hello,

I was trying to look at demos from your readme ( https://www.npmjs.com/package/@microblink/blinkid-imagecapture-in-browser-sdk / https://github.com/BlinkID/blinkid-imagecapture-in-browser?tab=readme-ov-file#blinkid-imagecapture-in-browser-sdk ), but it looks like some of them are not working because they are missing (404 on gh pages), and some of them (codepen ones) are not working because license key has expired. 

![image](https://github.com/BlinkID/blinkid-imagecapture-in-browser/assets/546845/47ab34f1-1be4-433e-9952-3249d940622b)

**Comment by somyaguptagit** [comment]
Hello @pavelloz Thank you for your inquiry!
We would encourage you to forward your inquiry to support@microblink.com and we can further look into the issue.

**Comment by pavelloz** [comment]
Can you do that for me? All the info is in my original post. Thank you.
